packages:
  - packages/*

catalogs:
  build:
    typescript: ^5.9.2
    vite: ^6.3.5
  format:
    "@ianvs/prettier-plugin-sort-imports": ^4.6.1
    prettier: 3.6.2
    prettier-plugin-packagejson: ^2.5.19
  lint:
    "@eslint/eslintrc": ^3.3.1
    "@eslint/js": ^9.33.0
    eslint: ^9.33.0
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: ^5.2.0
    jiti: ^2.5.1
    typescript-eslint: ^8.39.0
  script:
    taze: ^19.1.0
  slidev:
    "@slidev/cli": ^52.1.0
    "@slidev/types": ^52.1.0
    vue: ^3.5.18
    "prettier-plugin-slidev": "^1.0.5"
  test:
    "@playwright/test": ^1.54.2
    "@vitest/browser": ^3.2.4
    vitest: ^3.2.4
  types:
    "@types/node": ^22.17.1

ignoredBuiltDependencies:
  - esbuild
